USE anaitgames;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE table users;
TRUNCATE table posts;
TRUNCATE table tags;
TRUNCATE table posts_tags;
TRUNCATE table comments;
TRUNCATE table comment_reports;
TRUNCATE table mentions;
TRUNCATE table bans;
TRUNCATE table ip_bans;
SET FOREIGN_KEY_CHECKS = 1;